"""Uygulama ayarları"""

# Veritabanı
DATABASE_PATH = "data/portfolio.db"

# Varsayılan semboller
DEFAULT_SYMBOLS = {
    "BIST": [
        # BIST 100
        "AEFES.IS", "AFYON.IS", "AGESA.IS", "AKBNK.IS", "AKCNS.IS", "AKFGY.IS", "AKFYE.IS", "AKSA.IS",
        "AKSEN.IS", "ALARK.IS", "ALBRK.IS", "ALFAS.IS", "ALGYO.IS", "ALKIM.IS", "ALTNY.IS", "ALTIN.IS",
        "ANSGR.IS", "AGHOL.IS", "ARCLK.IS", "ARDYZ.IS", "ARENA.IS", "ASELS.IS", "ASGYO.IS", "ASTOR.IS",
        "AYDEM.IS", "AYEN.IS", "AYGAZ.IS", "AZTEK.IS", "BAGFS.IS", "BAKAB.IS", "BANVT.IS", "BARMA.IS",
        "BASGZ.IS", "BERA.IS", "BEYAZ.IS", "BFREN.IS", "BIENY.IS", "BIGCH.IS", "BIMAS.IS", "BIOEN.IS",
        "BIZIM.IS", "BJKAS.IS", "BLCYT.IS", "BMSCH.IS", "BMSTL.IS", "BNTAS.IS", "BOBET.IS", "BORLS.IS",
        "BORSK.IS", "BOSSA.IS", "BRISA.IS", "BRKO.IS", "BRKSN.IS", "BRKVY.IS", "BRLSM.IS", "BRMEN.IS",
        "BRSAN.IS", "BRYAT.IS", "BSOKE.IS", "BTCIM.IS", "BUCIM.IS", "BURCE.IS", "BURVA.IS", "BVSAN.IS",
        "CASA.IS", "CANTE.IS", "CCOLA.IS", "CELHA.IS", "CEMAS.IS", "CEMTS.IS", "CEOEM.IS", "CIMSA.IS",
        "CLEBI.IS", "CMBTN.IS", "CMENT.IS", "CONSE.IS", "COSMO.IS", "CRDFA.IS", "CRFSA.IS", "CUSAN.IS",
        "CVKMD.IS", "CWENE.IS", "DAGI.IS", "DAPGM.IS", "DARDL.IS", "DENGE.IS", "DERHL.IS", "DERIM.IS",
        "DESA.IS", "DESPC.IS", "DEVA.IS", "DGATE.IS", "DGGYO.IS", "DGNMO.IS", "DIRIT.IS", "DITAS.IS",
        "DJIST.IS", "DMSAS.IS", "DNISI.IS", "DOAS.IS", "DOBUR.IS", "DOCO.IS", "DOGUB.IS", "DOHOL.IS",
        "DOKTA.IS", "DURDO.IS", "DYOBY.IS", "DZGYO.IS", "EBEBK.IS", "ECILC.IS", "ECZYT.IS", "EDATA.IS",
        "EDIP.IS", "EGEEN.IS", "EGEPO.IS", "EGGUB.IS", "EGPRO.IS", "EGSER.IS", "EKGYO.IS", "EKIZ.IS",
        "EKOS.IS", "EKSUN.IS", "ELITE.IS", "EMKEL.IS", "EMNIS.IS", "ENERY.IS", "ENJSA.IS", "ENKAI.IS",
        "ENSRI.IS", "EPLAS.IS", "ERBOS.IS", "ERCB.IS", "EREGL.IS", "ERSU.IS", "ESCAR.IS", "ESCOM.IS",
        "ESEN.IS", "ETILR.IS", "ETYAT.IS", "EUHOL.IS", "EUKYO.IS", "EUPWR.IS", "EUREN.IS", "EUYO.IS",
        "EYGYO.IS", "FADE.IS", "FENER.IS", "FLAP.IS", "FMIZP.IS", "FONET.IS", "FORMT.IS", "FORTE.IS",
        "FROTO.IS", "FZLGY.IS", "GARAN.IS", "GARFA.IS", "GEDIK.IS", "GEDZA.IS", "GENIL.IS", "GENTS.IS",
        "GEREL.IS", "GESAN.IS", "GIPTS.IS", "GLBMD.IS", "GLCVY.IS", "GLYHO.IS", "GMTAS.IS", "GOKNR.IS",
        "GOLTS.IS", "GOODY.IS", "GOZDE.IS", "GRTRK.IS", "GSDDE.IS", "GSDHO.IS", "GSRAY.IS", "GUBRF.IS",
        "GUNDG.IS", "GWIND.IS", "GZNMI.IS", "HALKB.IS", "HATEK.IS", "HATSN.IS", "HDFGS.IS", "HEDEF.IS",
        "HEKTS.IS", "HKTM.IS", "HLGYO.IS", "HOROZ.IS", "HRKET.IS", "HTTBT.IS", "HUBVC.IS", "HUNER.IS",
        "HURGZ.IS", "ICBCT.IS", "ICUGS.IS", "IDEAS.IS", "IEYHO.IS", "IHAAS.IS", "IHEVA.IS", "IHGZT.IS",
        "IHLAS.IS", "IHLGM.IS", "IHYAY.IS", "IMASM.IS", "INDES.IS", "INFO.IS", "INGRM.IS", "INTEM.IS",
        "INVEO.IS", "INVES.IS", "IPEKE.IS", "ISDMR.IS", "ISFIN.IS", "ISGSY.IS", "ISGYO.IS", "ISMEN.IS",
        "ISSEN.IS", "ISYAT.IS", "IZENR.IS", "IZFAS.IS", "IZINV.IS", "IZMDC.IS", "JANTS.IS", "KAPLM.IS",
        "KAREL.IS", "KARSN.IS", "KARTN.IS", "KARYE.IS", "KATMR.IS", "KAYSE.IS", "KBORU.IS", "KCAER.IS",
        "KCHOL.IS", "KENT.IS", "KERVN.IS", "KERVT.IS", "KFEIN.IS", "KGYO.IS", "KIMMR.IS", "KLGYO.IS",
        "KLKIM.IS", "KLMSN.IS", "KLNMA.IS", "KLRHO.IS", "KLSER.IS", "KLSYN.IS", "KMPUR.IS", "KNFRT.IS",
        "KOCMT.IS", "KONKA.IS", "KONTR.IS", "KOPOL.IS", "KORDS.IS", "KOTON.IS", "KOZAA.IS", "KOZAL.IS",
        "KRDMA.IS", "KRDMB.IS", "KRDMD.IS", "KRGYO.IS", "KRONT.IS", "KRPLS.IS", "KRSTL.IS", "KRTEK.IS",
        "KRVGD.IS", "KSTUR.IS", "KTLEV.IS", "KTSKR.IS", "KUTPO.IS", "KUVVA.IS", "KUYAS.IS", "KZBGY.IS",
        "KZGYO.IS", "LIDER.IS", "LIDFA.IS", "LILAK.IS", "LINK.IS", "LKMNH.IS", "LMKDC.IS", "LOGO.IS",
        "LRSHO.IS", "LUKSK.IS", "MAALT.IS", "MACKO.IS", "MAGEN.IS", "MAKIM.IS", "MANAS.IS", "MARBL.IS",
        "MARKA.IS", "MARTI.IS", "MAVI.IS", "MEDTR.IS", "MEGAP.IS", "MEGMT.IS", "MEKAG.IS", "MERCN.IS",
        "MERIT.IS", "MERKO.IS", "METRO.IS", "METUR.IS", "MGROS.IS", "MHRGY.IS", "MIATK.IS", "MIPAZ.IS",
        "MMCAS.IS", "MNDRS.IS", "MNDTR.IS", "MOBTL.IS", "MOGAN.IS", "MPARK.IS", "MRGYO.IS", "MRSHL.IS",
        "MSGYO.IS", "MTRKS.IS", "MTRYO.IS", "MZHLD.IS", "NATEN.IS", "NETAS.IS", "NIBAS.IS", "NTHOL.IS",
        "NUGYO.IS", "NUHCM.IS", "OBAMS.IS", "OBASE.IS", "ODAS.IS", "ODINE.IS", "OFSYM.IS", "ONCSM.IS",
        "ONRYT.IS", "ORCAY.IS", "ORGE.IS", "ORMA.IS", "OSMEN.IS", "OSTIM.IS", "OTKAR.IS", "OTTO.IS",
        "OYAKC.IS", "OYAYO.IS", "OYLUM.IS", "OYYAT.IS", "OZGYO.IS", "OZKGY.IS", "OZRDN.IS", "OZSUB.IS",
        "OZYSR.IS", "PAMEL.IS", "PAPIL.IS", "PARSN.IS", "PASEU.IS", "PATEK.IS", "PCILT.IS", "PEGYO.IS",
        "PEKGY.IS", "PENGD.IS", "PENTA.IS", "PETKM.IS", "PETUN.IS", "PGSUS.IS", "PINSU.IS", "PKART.IS",
        "PKENT.IS", "PLTUR.IS", "PNLSN.IS", "PNSUT.IS", "POLHO.IS", "POLTK.IS", "PRDGS.IS", "PRKAB.IS",
        "PRKME.IS", "PRZMA.IS", "PSDTC.IS", "PSGYO.IS", "QUAGR.IS", "RALYH.IS", "RAYSG.IS", "REEDR.IS",
        "RGYAS.IS", "RHGYO.IS", "RNPOL.IS", "RODRG.IS", "ROYAL.IS", "RTALB.IS", "RUBNS.IS", "RYGYO.IS",
        "RYSAS.IS", "SAFKR.IS", "SAHOL.IS", "SAMAT.IS", "SANEL.IS", "SANFM.IS", "SANKO.IS", "SARKY.IS",
        "SASA.IS", "SAYAS.IS", "SDTTR.IS", "SEGYO.IS", "SEKFK.IS", "SEKUR.IS", "SELEC.IS", "SELGD.IS",
        "SELVA.IS", "SEYKM.IS", "SILVR.IS", "SISE.IS", "SKBNK.IS", "SKTAS.IS", "SMART.IS", "SMRTG.IS",
        "SNGYO.IS", "SNICA.IS", "SNKRN.IS", "SNPAM.IS", "SODSN.IS", "SOKM.IS", "SONME.IS", "SRVGY.IS",
        "SUNTK.IS", "SUWEN.IS", "TATGD.IS", "TAVHL.IS", "TBORG.IS", "TCELL.IS", "TDGYO.IS", "TEKTU.IS",
        "TERA.IS", "TEZOL.IS", "TGSAS.IS", "THYAO.IS", "TIRE.IS", "TKFEN.IS", "TKNSA.IS", "TLMAN.IS",
        "TMPOL.IS", "TMSN.IS", "TOASO.IS", "TRCAS.IS", "TRGYO.IS", "TRILC.IS", "TSGYO.IS", "TSKB.IS",
        "TSPOR.IS", "TTKOM.IS", "TTRAK.IS", "TUCLK.IS", "TUKAS.IS", "TUPRS.IS", "TUREX.IS", "TURGG.IS",
        "TURSG.IS", "UFUK.IS", "ULAS.IS", "ULKER.IS", "ULUFA.IS", "ULUSE.IS", "ULUUN.IS", "UMPAS.IS",
        "UNLU.IS", "USAK.IS", "UZERB.IS", "VAKBN.IS", "VAKFN.IS", "VAKKO.IS", "VANGD.IS", "VBTYZ.IS",
        "VERTU.IS", "VERUS.IS", "VESBE.IS", "VESTL.IS", "VKFYO.IS", "VKGYO.IS", "VKING.IS", "YAPRK.IS",
        "YATAS.IS", "YAYLA.IS", "YBTAS.IS", "YEOTK.IS", "YESIL.IS", "YGGYO.IS", "YGYO.IS", "YKBNK.IS",
        "YKSLN.IS", "YONGA.IS", "YUNSA.IS", "YYAPI.IS", "YYLGD.IS", "ZEDUR.IS", "ZELOT.IS", "ZOREN.IS",
        "ZRGYO.IS"
    ],
    "ABD": [
        # S&P 500 ve Popüler Hisseler
        "AAPL", "MSFT", "GOOGL", "GOOG", "AMZN", "NVDA", "META", "TSLA", "BRK-B", "UNH",
        "JNJ", "JPM", "V", "PG", "XOM", "HD", "CVX", "MA", "ABBV", "MRK",
        "LLY", "PEP", "KO", "AVGO", "COST", "TMO", "MCD", "WMT", "CSCO", "ACN",
        "ABT", "DHR", "BAC", "PFE", "CRM", "NKE", "CMCSA", "DIS", "VZ", "ADBE",
        "TXN", "NFLX", "PM", "WFC", "NEE", "RTX", "BMY", "UNP", "ORCL", "HON",
        "QCOM", "COP", "LOW", "UPS", "INTC", "IBM", "AMGN", "SPGI", "CAT", "BA",
        "GE", "INTU", "AMD", "AMAT", "DE", "SBUX", "GS", "MS", "BLK", "ELV",
        "MDLZ", "ISRG", "ADI", "GILD", "AXP", "LMT", "BKNG", "REGN", "CVS", "TJX",
        "VRTX", "SYK", "TMUS", "ZTS", "PGR", "CB", "MMC", "SCHW", "CI", "SO",
        "LRCX", "MO", "DUK", "BDX", "EOG", "CME", "SLB", "AON", "NOC", "ITW",
        "PYPL", "ICE", "CL", "EQIX", "WM", "SNPS", "CSX", "SHW", "APD", "MMM",
        "MU", "FDX", "GM", "F", "EMR", "PNC", "FCX", "GD", "PSX", "ORLY",
        "ADP", "NSC", "MCK", "TGT", "MCO", "TFC", "ROP", "MPC", "ADSK", "USB",
        "EW", "KDP", "MNST", "VLO", "KLAC", "MCHP", "PSA", "AIG", "MSCI", "OXY",
        "NEM", "FTNT", "PAYX", "KMB", "A", "AEP", "CTVA", "GIS", "SRE", "AFL",
        "TEL", "AZO", "O", "CDNS", "D", "CTAS", "CHTR", "HUM", "PXD", "PCAR",
        "IDXX", "JCI", "DXCM", "WELL", "CMG", "DOW", "HES", "CARR", "SPG", "DHI",
        "MRVL", "TRV", "ALL", "KHC", "YUM", "IQV", "PRU", "LEN", "HAL", "MTD",
        "BK", "STZ", "AJG", "ROST", "CMI", "FAST", "GWW", "DLR", "AME", "EA",
        "PCG", "OTIS", "EXC", "KR", "NDAQ", "HSY", "ON", "WMB", "ED", "BAX",
        "CTSH", "BIIB", "VRSK", "ALB", "APTV", "PPG", "RMD", "CPRT", "CBRE", "XEL",
        "HLT", "KEYS", "AWK", "ANSS", "VICI", "FANG", "CDW", "WST", "DFS", "ROK",
        "EFX", "GEHC", "EBAY", "PEG", "ACGL", "ODFL", "FTV", "EIX", "WEC", "VMC",
        "WTW", "GLW", "LYB", "TSCO", "DAL", "IT", "URI", "CAH", "ILMN", "DVN",
        "SBAC", "HPQ", "CSGP", "MTB", "ZBH", "ARE", "GPN", "FIS", "FITB", "TTWO",
        "LUV", "CHD", "STT", "LH", "TROW", "ES", "PPL", "ULTA", "NVR", "HOLX",
        "HBAN", "RF", "CNP", "WBA", "PWR", "TDY", "K", "COO", "BR", "DTE",
        "MAA", "NTRS", "FE", "LVS", "STE", "WAT", "CLX", "CINF", "ATO", "VTR",
        "CFG", "AVB", "CNC", "BALL", "CE", "J", "EXPD", "WAB", "MKC", "ESS",
        "AES", "CAG", "OMC", "DRI", "BRO", "IP", "SYY", "POOL", "IRM", "SWK",
        "AMCR", "AKAM", "MGM", "KEY", "WRB", "SNA", "TRMB", "TXT", "TER", "KIM",
        "BXP", "CCL", "NRG", "APA", "PFG", "L", "UDR", "HRL", "PKG", "JNPR",
        "CPT", "EMN", "TECH", "REG", "CPB", "TAP", "VTRS", "BEN", "SJM", "HSIC",
        "NDSN", "FFIV", "LKQ", "RHI", "CHRW", "AIZ", "HII", "MHK", "IEX", "CRL",
        "BIO", "BBWI", "BWA", "AAL", "ALLE", "FRT", "NWL", "PNR", "SEE", "HAS",
        "MTCH", "PARA", "VFC", "WYNN", "XRAY", "DVA", "FMC", "WHR", "ZION", "ALK",
        "NCLH", "CMA", "RCL", "MOS", "DXC", "DISH", "UAL", "GNRC", "ETSY", "PAYC",
        "COIN", "RIVN", "LCID", "PLTR", "SOFI", "HOOD", "AFRM", "UPST", "RBLX", "U",
        "SNAP", "PINS", "ZM", "DOCU", "CRWD", "DDOG", "NET", "ZS", "OKTA", "MDB",
        "SNOW", "SHOP", "SQ", "UBER", "LYFT", "ABNB", "DASH", "GRAB", "SE", "MELI"
    ],
    "Kripto": [
        # Top 500 Kripto Para (Market Cap sıralı)
        "BTC-USD", "ETH-USD", "USDT-USD", "BNB-USD", "SOL-USD", "XRP-USD", "USDC-USD", "STETH-USD",
        "ADA-USD", "DOGE-USD", "TRX-USD", "AVAX-USD", "LINK-USD", "TON-USD", "SHIB-USD", "DOT-USD",
        "BCH-USD", "NEAR-USD", "MATIC-USD", "LTC-USD", "UNI-USD", "ICP-USD", "LEO-USD", "DAI-USD",
        "APT-USD", "ETC-USD", "RNDR-USD", "FET-USD", "HBAR-USD", "STX-USD", "IMX-USD", "CRO-USD",
        "FIL-USD", "MNT-USD", "ATOM-USD", "KAS-USD", "ARB-USD", "MKR-USD", "VET-USD", "OP-USD",
        "XLM-USD", "INJ-USD", "GRT-USD", "RUNE-USD", "TAO-USD", "THETA-USD", "SUI-USD", "FTM-USD",
        "ALGO-USD", "SEI-USD", "LDO-USD", "TIA-USD", "AR-USD", "FLOW-USD", "AAVE-USD", "EGLD-USD",
        "AXS-USD", "SAND-USD", "MANA-USD", "GALA-USD", "APE-USD", "CHZ-USD", "XTZ-USD", "NEO-USD",
        "KLAY-USD", "IOTA-USD", "CAKE-USD", "MINA-USD", "EOS-USD", "XEC-USD", "ROSE-USD", "KAVA-USD",
        "BTT-USD", "CFX-USD", "SNX-USD", "LUNC-USD", "ASTR-USD", "1INCH-USD", "DASH-USD", "ZEC-USD",
        "COMP-USD", "CRV-USD", "DYDX-USD", "ENJ-USD", "BAT-USD", "HOT-USD", "ZIL-USD", "QTUM-USD",
        "ANKR-USD", "LRC-USD", "ENS-USD", "RVN-USD", "ICX-USD", "CELO-USD", "GMT-USD", "GLM-USD",
        "JST-USD", "AUDIO-USD", "KSM-USD", "YFI-USD", "SC-USD", "ONE-USD", "OMG-USD", "ZRX-USD",
        "WOO-USD", "CVX-USD", "STORJ-USD", "MASK-USD", "SKL-USD", "BORA-USD", "CELR-USD", "SXP-USD",
        "UMA-USD", "RSR-USD", "RLC-USD", "CTSI-USD", "BAND-USD", "OCEAN-USD", "SUPER-USD", "DENT-USD",
        "COTI-USD", "MTL-USD", "REEF-USD", "FET-USD", "AGIX-USD", "NKN-USD", "STMX-USD", "OGN-USD",
        "HIVE-USD", "SLP-USD", "ALICE-USD", "TLM-USD", "DAR-USD", "PEOPLE-USD", "JASMY-USD", "LINA-USD",
        "ARDR.IS", "PUNDIX-USD", "BETA-USD", "BURGER-USD", "WING-USD", "FIDA-USD", "RARE-USD", "ADX-USD",
        "PERP-USD", "SPELL-USD", "JOE-USD", "HIGH-USD", "AMB-USD", "AERGO-USD", "VIDT-USD", "CHESS-USD",
        "FORTH-USD", "FARM-USD", "ALCX-USD", "ERN-USD", "BADGER-USD", "BOND-USD", "TRU-USD", "ALPHA-USD",
        "POLS-USD", "DF-USD", "IDEX-USD", "POND-USD", "TVK-USD", "SFP-USD", "LAZIO-USD", "PORTO-USD",
        "SANTOS-USD", "ATM-USD", "ACM-USD", "BAR-USD", "JUV-USD", "PSG-USD", "CITY-USD", "ASR-USD",
        "OG-USD", "BIFI-USD", "DEGO-USD", "FOR-USD", "CREAM-USD", "EASY-USD", "AUTO-USD", "EPS-USD",
        "NBS-USD", "HEGIC-USD", "KP3R-USD", "COVER-USD", "UNFI-USD", "HARD-USD", "CVP-USD", "FRONT-USD",
        "DOCK-USD", "COS-USD", "MBOX-USD", "GHST-USD", "QUICK-USD", "RAD-USD", "MIR-USD", "ANC-USD",
        "TORN-USD", "KEEP-USD", "NU-USD", "BEL-USD", "WING-USD", "CREAM-USD", "SUN-USD", "YFII-USD",
        "BNT-USD", "REP-USD", "REN-USD", "BAL-USD", "SUSHI-USD", "KNC-USD", "ANT-USD", "NMR-USD",
        "MLN-USD", "DNT-USD", "LOOM-USD", "MITH-USD", "KEY-USD", "GAS-USD", "POWR-USD", "BLZ-USD",
        "DATA-USD", "AGI-USD", "PHB-USD", "WAN-USD", "FUN-USD", "MITH-USD", "GTO-USD", "APPC-USD",
        "VIBE-USD", "PIVX-USD", "GRS-USD", "SKY-USD", "GXS-USD", "LEND-USD", "CDT-USD", "QKC-USD",
        "GO-USD", "PAX-USD", "DUSK-USD", "BCPT-USD", "QSP-USD", "CVC-USD", "TNT-USD", "FUEL-USD",
        "MDA-USD", "MTH-USD", "DGD-USD", "EDO-USD", "WINGS-USD", "NAV-USD", "TRIG-USD", "SNGLS-USD",
        "SNT-USD", "SALT-USD", "RCN-USD", "VIB-USD", "OST-USD", "POE-USD", "LUN-USD", "CHAT-USD",
        "MOD-USD", "EVX-USD", "RPX-USD", "VIA-USD", "BCD-USD", "WABI-USD", "NULS-USD", "WTC-USD",
        "TNB-USD", "GVT-USD", "POA-USD", "SUB-USD", "BTS-USD", "PPT-USD", "CMT-USD", "WPR-USD",
        "INS-USD", "BRD-USD", "AE-USD", "NCASH-USD", "CLOAK-USD", "MOD-USD", "SKY-USD", "SYS-USD",
        "STORJ-USD", "ELF-USD", "AION-USD", "NEBL-USD", "ARK-USD", "XVG-USD", "STRAT-USD", "DCR-USD",
        "LSK-USD", "WAVES-USD", "DGB-USD", "ZEN-USD", "NANO-USD", "PAC-USD", "BTG-USD", "BCN-USD",
        "XMR-USD", "REQ-USD", "FTT-USD", "BAKE-USD", "WIN-USD", "AKRO-USD", "FIS-USD", "TRIBE-USD",
        "RAY-USD", "SRM-USD", "FIDA-USD", "MAPS-USD", "OXY-USD", "STEP-USD", "COPE-USD", "MNGO-USD",
        "SLND-USD", "PORT-USD", "SNY-USD", "ORCA-USD", "SABER-USD", "TULIP-USD", "SUNNY-USD", "JET-USD",
        "MEDIA-USD", "KIN-USD", "GENE-USD", "LIKE-USD", "STAR-USD", "SAMO-USD", "CHEEMS-USD", "WOOF-USD",
        "BONK-USD", "MYRO-USD", "WIF-USD", "BOME-USD", "POPCAT-USD", "MEW-USD", "PONKE-USD", "SLERF-USD",
        "TRUMP-USD", "TREMP-USD", "BODEN-USD", "MOTHER-USD", "DADDY-USD", "GME-USD", "PEPE-USD", "FLOKI-USD",
        "BABYDOGE-USD", "ELON-USD", "SAITAMA-USD", "LEASH-USD", "BONE-USD", "CULT-USD", "LUNC-USD", "USTC-USD",
        "MIM-USD", "FRAX-USD", "LUSD-USD", "TUSD-USD", "USDP-USD", "GUSD-USD", "EURS-USD", "EURT-USD",
        "XAUT-USD", "PAXG-USD", "DGX-USD", "WBTC-USD", "RENBTC-USD", "HBTC-USD", "TBTC-USD", "SBTC-USD",
        "OBTC-USD", "BBTC-USD", "FBTC-USD", "EBTC-USD", "CBTC-USD", "RBTC-USD", "BTCB-USD", "BTCST-USD",
        "BTCUP-USD", "BTCDOWN-USD", "ETHUP-USD", "ETHDOWN-USD", "BNBUP-USD", "BNBDOWN-USD", "XRPUP-USD",
        "XRPDOWN-USD", "DOTUP-USD", "DOTDOWN-USD", "LTCUP-USD", "LTCDOWN-USD", "LINKUP-USD", "LINKDOWN-USD",
        "AXL-USD", "PYTH-USD", "JTO-USD", "JITO-USD", "WEN-USD", "ONDO-USD", "ENA-USD", "ETHFI-USD",
        "SAGA-USD", "TNSR-USD", "REZ-USD", "BB-USD", "NOT-USD", "IO-USD", "ZK-USD", "LISTA-USD",
        "ZRO-USD", "BLAST-USD", "AEVO-USD", "W-USD", "KMNO-USD", "CLOUD-USD", "SAFE-USD", "EIGEN-USD",
        "SCR-USD", "PUFFER-USD", "CATI-USD", "HMSTR-USD", "DOGS-USD", "MAJOR-USD", "BANANA-USD", "SUNDOG-USD"
    ]
}

# Zaman dilimleri
PERIODS = {
    "1 Gün": "1d",
    "5 Gün": "5d",
    "1 Ay": "1mo",
    "3 Ay": "3mo",
    "6 Ay": "6mo",
    "1 Yıl": "1y",
    "2 Yıl": "2y",
    "5 Yıl": "5y",
    "Tümü": "max"
}

# Aralıklar
INTERVALS = {
    "1 Dakika": "1m",
    "5 Dakika": "5m",
    "15 Dakika": "15m",
    "1 Saat": "1h",
    "1 Gün": "1d",
    "1 Hafta": "1wk",
    "1 Ay": "1mo"
}

# Teknik analiz ayarları
TECHNICAL_SETTINGS = {
    "SMA_PERIODS": [20, 50, 200],
    "EMA_PERIODS": [12, 26],
    "RSI_PERIOD": 14,
    "MACD_FAST": 12,
    "MACD_SLOW": 26,
    "MACD_SIGNAL": 9,
    "BB_PERIOD": 20,
    "BB_STD": 2
}
